apiVersion: v1
kind: Secret

metadata:
  name: fintech-backend-secret

type: Opaque

stringData:
  SECRET_KEY: "your-secrete-key"
  JWT_SECRET_KEY: "zorlams-jwt-secret-key"
  DATABASE_URL: "making-use-of-a-placeholder"
  FRONTEND_ORIGIN: "http://localhost:3000"
  JWT_REFRESH_TOKEN_EXPIRES_DAYS: "7"
  