apiVersion: v1
kind: Service

metadata:
  name: fintech-backend-service

spec:
  selector:
    app: fintech-backend

  ports:
    - protocol: TCP
      port: 5050
      targetPort: 5050

  type: NodePort